import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

// BEGIN/END markers let us detect and cleanly re-install over an existing
// minspect plugin file. Anything outside the markers is treated as foreign
// (user-authored) and preserved via a .bak.<ts> backup when we overwrite.
export const BEGIN_MARKER = '// >>> minspect managed >>>';
export const END_MARKER = '// <<< minspect managed <<<';

export interface InstallOpenCodeOptions {
  pluginPath?: string; // override for tests
  aiHistoryBin?: string; // command the plugin spawns per event
  scope?: 'user' | 'project';
}

export interface InstallOpenCodeResult {
  path: string;
  backup?: string;
  wrote: boolean;
}

function defaultPluginPath(scope: 'user' | 'project'): string {
  if (scope === 'user') return join(homedir(), '.config', 'opencode', 'plugins', 'minspect.ts');
  return join(process.cwd(), '.opencode', 'plugins', 'minspect.ts');
}

// Plugin file template. Kept as a raw string so we can embed the minspect
// binary path without escaping gymnastics. The file subscribes three hooks
// (`event`, `tool.execute.before`, `tool.execute.after`) and for each one
// spawns a detached `minspect capture-opencode` subprocess, piping the
// envelope JSON to stdin. Fire-and-forget — nothing in the hook path
// blocks or throws into OpenCode.
export function pluginTemplate(minspectBin: string, binTag: string): string {
  // Escape backslashes (Windows paths) and double-quotes for JS string
  // literal safety.
  const escaped = minspectBin.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `${BEGIN_MARKER}
// Auto-generated by \`minspect install --agent opencode\`. Edit the outer
// file around these markers freely — running install again only replaces
// the block between the >>> and <<< markers. ${binTag}
import type { Plugin } from '@opencode-ai/plugin';
import { spawn } from 'node:child_process';
import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir, platform } from 'node:os';

const MINSPECT_BIN = process.env.MINSPECT_BIN || "${escaped}";
const NODE_BIN = process.env.MINSPECT_NODE || 'node';

// Diagnostic: write a marker file on plugin load + every hook fire so we
// can verify via the filesystem that OpenCode is actually picking us up.
// Disabled by setting MINSPECT_QUIET=1.
const MINSPECT_STATE_DIR = (() => {
  if (platform() === 'win32') {
    return process.env.LOCALAPPDATA
      ? join(process.env.LOCALAPPDATA, 'minspect')
      : join(homedir(), 'AppData', 'Local', 'minspect');
  }
  return process.env.XDG_STATE_HOME
    ? join(process.env.XDG_STATE_HOME, 'minspect')
    : join(homedir(), '.local', 'state', 'minspect');
})();
const PLUGIN_LOG = join(MINSPECT_STATE_DIR, 'opencode-plugin.log');

function diag(line: string): void {
  if (process.env.MINSPECT_QUIET === '1') return;
  try {
    appendFileSync(PLUGIN_LOG, \`[\${new Date().toISOString()}] \${line}\\n\`);
  } catch {
    // ignore — plugin must never throw
  }
}

try {
  writeFileSync(
    join(MINSPECT_STATE_DIR, 'opencode-plugin-loaded.txt'),
    \`loaded at \${new Date().toISOString()}\\nbin: \${MINSPECT_BIN}\\nnode: \${NODE_BIN}\\nexecPath: \${process.execPath}\\n\`,
  );
} catch {
  /* ignore */
}

// OpenCode itself is a native binary (the embedded Bun runtime loads this
// plugin), so \`process.execPath\` is opencode.exe — useless as a JS
// interpreter. For .js/.mjs/.cjs entrypoints we spawn \`node\` via PATH;
// users who don't have node on PATH can override by setting
// \`MINSPECT_NODE\`. For installed npm binaries (\`.cmd\` / \`.exe\` / Unix
// shim) we spawn directly.
function resolveSpawn(): { cmd: string; args: string[] } {
  const bin = MINSPECT_BIN;
  const lower = bin.toLowerCase();
  if (lower.endsWith('.js') || lower.endsWith('.mjs') || lower.endsWith('.cjs')) {
    return { cmd: NODE_BIN, args: [bin, 'capture-opencode'] };
  }
  return { cmd: bin, args: ['capture-opencode'] };
}

// Only the events that actually produce a minspect Event or prime state are
// forwarded. OpenCode's event hook fires on EVERY token of a streaming
// response (message.part.updated for incremental text / reasoning / running
// tool state) — forwarding all of them would spawn a new child process per
// token and on Windows each spawn can flash a console window. Filtering in
// the plugin itself brings spawn rate down from hundreds/sec to ~1-20 per
// turn.
function shouldForward(event: Record<string, unknown>): boolean {
  const t = event.type;
  if (t === 'session.created' || t === 'session.deleted' || t === 'session.idle') return true;
  const props = (event.properties as Record<string, unknown> | undefined) ?? {};
  if (t === 'message.updated') {
    const info = props.info as { role?: string; time?: { completed?: number } } | undefined;
    if (!info) return false;
    if (info.role === 'user') return true;
    if (info.role === 'assistant' && info.time && info.time.completed != null) return true;
    return false;
  }
  if (t === 'message.part.updated') {
    const part = props.part as { type?: string; state?: { status?: string }; time?: { end?: number } } | undefined;
    if (!part) return false;
    if (part.type === 'tool') {
      const status = part.state && part.state.status;
      return status === 'completed' || status === 'error';
    }
    // Reasoning streams heavily (incremental token deltas) — gate on time.end
    // so only the terminal update is forwarded.
    if (part.type === 'reasoning') {
      return !!(part.time && part.time.end != null);
    }
    // Text parts are low-volume (1-2 per message) and user TextParts
    // sometimes never get a time.end — always forward.
    if (part.type === 'text') return true;
    return false;
  }
  return false;
}

function fireAndForget(payload: unknown): void {
  try {
    const { cmd, args } = resolveSpawn();
    // IMPORTANT: no \`detached: true\` on Windows — it forces a new console
    // window and windowsHide doesn't reliably suppress it. The child runs in
    // the same session as OpenCode, which is fine because capture-opencode
    // finishes in milliseconds.
    const child = spawn(cmd, args, {
      stdio: ['pipe', 'ignore', 'ignore'],
      windowsHide: true,
    });
    child.on('error', () => {});
    if (child.stdin) {
      try { child.stdin.end(JSON.stringify(payload)); } catch {}
    }
    child.unref();
  } catch {
    // hooks never block the agent
  }
}

function safeReadFile(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

export const MinspectPlugin: Plugin = async () => {
  diag('plugin factory invoked');
  return {
    event: async ({ event }) => {
      const ev = event as Record<string, unknown>;
      if (!shouldForward(ev)) {
        diag(\`event skipped: \${String(ev.type)}\`);
        return;
      }
      diag(\`event forward: \${String(ev.type)}\`);
      fireAndForget({ hookName: 'event', payload: ev, timestamp: Date.now() });
    },
    'tool.execute.before': async (input, output) => {
      // For file-edit tools, snapshot the current file content so the
      // collector can record a proper before_content alongside the edit.
      // OpenCode's built-in edit/write tools use camelCase args
      // (\`filePath\`); we probe a couple of alternate keys for safety.
      let minspect_before: string | null = null;
      try {
        const args = (output && output.args && typeof output.args === 'object')
          ? (output.args as Record<string, unknown>)
          : {};
        const fp = (typeof args.filePath === 'string' && args.filePath)
          || (typeof args.file_path === 'string' && args.file_path)
          || (typeof args.path === 'string' && args.path)
          || undefined;
        if ((input.tool === 'edit' || input.tool === 'write') && typeof fp === 'string') {
          minspect_before = safeReadFile(fp);
        }
      } catch { /* ignore */ }
      const args = output && output.args ? { ...output.args, _minspect_before_content: minspect_before } : { _minspect_before_content: minspect_before };
      fireAndForget({
        hookName: 'tool.before',
        payload: { ...input, args },
        timestamp: Date.now(),
      });
    },
    'tool.execute.after': async (input, output) => {
      fireAndForget({
        hookName: 'tool.after',
        payload: { ...input, output },
        timestamp: Date.now(),
      });
    },
  };
};

export default MinspectPlugin;
${END_MARKER}
`;
}

// Returns true when the file contains our managed block so we can overwrite
// cleanly (it's our content, and the install is idempotent).
function isOurFile(content: string): boolean {
  return content.includes(BEGIN_MARKER) && content.includes(END_MARKER);
}

export function runInstallOpenCode(options: InstallOpenCodeOptions): InstallOpenCodeResult {
  const pluginPath = options.pluginPath ?? defaultPluginPath(options.scope ?? 'user');
  const bin = options.aiHistoryBin ?? process.argv[1] ?? 'minspect';
  const binTag = `bin=${bin}`;
  const content = pluginTemplate(bin, binTag);

  let backup: string | undefined;
  if (existsSync(pluginPath)) {
    const existing = readFileSync(pluginPath, 'utf8');
    if (!isOurFile(existing)) {
      // Foreign file — preserve before overwrite.
      const ts = new Date().toISOString().replace(/[:.]/g, '-');
      backup = `${pluginPath}.bak.${ts}`;
      copyFileSync(pluginPath, backup);
    } else {
      // Idempotent re-install: always take a backup of the previous managed
      // version too, so users can revert a bad upgrade.
      const ts = new Date().toISOString().replace(/[:.]/g, '-');
      backup = `${pluginPath}.bak.${ts}`;
      copyFileSync(pluginPath, backup);
    }
  }

  mkdirSync(dirname(pluginPath), { recursive: true });
  writeFileSync(pluginPath, content);
  return { path: pluginPath, backup, wrote: true };
}
