import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { getStateDir } from '../../paths.js';
import type { AutostartContext, AutostartPlan } from './index.js';

// Windows autostart backend: a per-user Run-key entry under
// HKCU\Software\Microsoft\Windows\CurrentVersion\Run.
//
// We previously tried Task Scheduler (`schtasks /Create /SC ONLOGON`)
// but creating an ONLOGON task from a non-elevated shell returns
// "Access is denied" — ONLOGON triggers need admin to wire up the
// session-attached token. The HKCU Run key, by contrast, is plain
// per-user state that any interactive user can write, and Explorer
// launches it at logon (same UX as ONLOGON for our headless daemon).
//
// The Run value does NOT name node.exe directly. node.exe is a console
// subsystem binary, so a Run-key launch opens a visible console window
// on the desktop — and closing that window kills the daemon (this is
// exactly what happened in the field: daemon vanished minutes after
// logon with no crash trace). Instead the value launches wscript.exe
// with a generated wrapper script in the state dir; the wrapper runs
// `node bin.cjs serve --quiet` with window style 0 (hidden) and does
// not wait, mirroring spawnServeDetached()'s detached + windowsHide
// spawn used by the hook / init paths.
//
// Paths are stored verbatim — no backslash doubling. reg.exe receives
// the /d data through a normal argv element and stores it literally
// (the earlier escapeReg assumption that reg.exe treats `\` as an
// escape was wrong; doubled backslashes ended up in the registry and
// only worked because Win32 path normalization tolerates them). Inside
// the VBS string literal, quotes are escaped by doubling them per
// VBScript rules.

const RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';
const RUN_VALUE = 'minspect-daemon';
const VBS_FILE = 'minspect-daemon.vbs';

// The launcher process. Bare name on purpose: Explorer's logon session
// always resolves System32, and an absolute path would force us through
// SystemRoot env parsing (case drift) for no real gain — wscript.exe is
// an OS component, not a user installation.
const VBS_LAUNCHER = 'wscript.exe';

// The wrapper path as it must appear in the Run value and inside wscript's
// command line: ALWAYS Windows separators, regardless of the host building
// the registration (CI runs the planner on Linux, where path.join would
// splice in "/" and store a mixed-separator path that only works by luck).
export function daemonVbsPath(ctx: AutostartContext): string {
  const base = (ctx.stateRoot || getStateDir()).replace(/[\\/]+$/, '');
  return `${base}\\${VBS_FILE}`;
}

// The same wrapper on this host's filesystem — the path execute/remove
// actually touch. On a real Windows install this is byte-identical to
// daemonVbsPath(); on non-Windows hosts (tests) it stays a valid path.
function daemonVbsFsPath(ctx: AutostartContext): string {
  return join(ctx.stateRoot || getStateDir(), VBS_FILE);
}

// VBScript string literal: double quotes are escaped by doubling.
function vbsStringLiteral(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

// Full wrapper body. Kept as one Run statement so wscript exits
// immediately after handing off to node.
export function buildVbsBody(ctx: AutostartContext): string {
  const { nodePath, minspectBinPath } = ctx.paths;
  const command = `"${nodePath}" "${minspectBinPath}" serve --quiet`;
  return [
    "' minspect daemon autostart (HKCU Run key backend).",
    `' Generated by \`minspect install-autostart\` — do not edit; re-run`,
    `' the command to regenerate after moving node or the minspect package.`,
    `' Window style 0 = hidden, False = don't wait: keeps the daemon`,
    `' headless, mirroring spawnServeDetached()'s detached spawn.`,
    `CreateObject("WScript.Shell").Run ${vbsStringLiteral(command)}, 0, False`,
    '',
  ].join('\r\n');
}

// The REG_SZ data Explorer executes at logon: launcher + wrapper script.
export function buildRunValue(ctx: AutostartContext): string {
  return `${VBS_LAUNCHER} "${daemonVbsPath(ctx)}"`;
}

export function planScheduledTask(ctx: AutostartContext): AutostartPlan {
  const runValue = buildRunValue(ctx);
  return {
    backend: 'scheduled-task',
    unitPath: `${RUN_KEY}\\${RUN_VALUE}`,
    unitBody: runValue,
    enable: {
      cmd: 'reg',
      args: ['add', RUN_KEY, '/v', RUN_VALUE, '/t', 'REG_SZ', '/d', runValue, '/f'],
    },
    disable: {
      cmd: 'reg',
      args: ['delete', RUN_KEY, '/v', RUN_VALUE, '/f'],
    },
    isInstalled: () => {
      try {
        execFileSync('reg', ['query', RUN_KEY, '/v', RUN_VALUE], {
          stdio: ['ignore', 'ignore', 'ignore'],
        });
        return true;
      } catch {
        return false;
      }
    },
  };
}

export function executeScheduledTask(plan: AutostartPlan, ctx: AutostartContext): void {
  // Write the wrapper before registering the Run value so a logon
  // between the two steps can't hit a dangling value. The state dir
  // normally exists by now; create it defensively for fresh installs.
  const vbsPath = daemonVbsFsPath(ctx);
  mkdirSync(dirname(vbsPath), { recursive: true });
  // UTF-16 LE with BOM: WScript detects the BOM, so non-ASCII install
  // paths survive regardless of the system codepage.
  const body = Buffer.concat([
    Buffer.from([0xff, 0xfe]),
    Buffer.from(buildVbsBody(ctx), 'utf16le'),
  ]);
  writeFileSync(vbsPath, body);
  // reg.exe returns exit 0 on successful add, even when the value
  // already exists (because of /f). stderr is intentionally ignored
  // — reg.exe prints "The operation completed successfully." on stdout
  // and we'd rather not leak that into CLI output.
  execFileSync(plan.enable.cmd, plan.enable.args, { stdio: 'ignore' });
}

export function removeScheduledTask(plan: AutostartPlan, ctx: AutostartContext): void {
  try {
    execFileSync(plan.disable.cmd, plan.disable.args, { stdio: 'ignore' });
  } catch {
    /* not installed */
  }
  // Best-effort wrapper cleanup: a missing file (or a stateRoot that
  // moved since install) leaves nothing to do — uninstall must not
  // fail over it.
  try {
    rmSync(daemonVbsFsPath(ctx), { force: true });
  } catch {
    /* ignore */
  }
}

// Exported for unit tests. Not part of the public surface — install-autostart
// goes through planScheduledTask, never these helpers directly.
export const __testing__ = { daemonVbsPath, buildVbsBody, buildRunValue, vbsStringLiteral };
